const area = [
  {
    province_number: '0011',
    province_name: '北京',
    cities: [{ city_number: '1100', city_name: '北京' }],
  },
  {
    province_number: '0012',
    province_name: '天津',
    cities: [{ city_number: '1200', city_name: '天津' }],
  },
  {
    province_number: '0013',
    province_name: '河北',
    cities: [
      { city_number: '1301', city_name: '石家庄' },
      { city_number: '1302', city_name: '保定' },
      { city_number: '1303', city_name: '沧州' },
      { city_number: '1304', city_name: '承德' },
      { city_number: '1305', city_name: '邯郸' },
      { city_number: '1306', city_name: '衡水' },
      { city_number: '1307', city_name: '廊坊' },
      { city_number: '1308', city_name: '秦皇岛' },
      { city_number: '1309', city_name: '唐山' },
      { city_number: '1310', city_name: '邢台' },
      { city_number: '1311', city_name: '张家口' },
    ],
  },
  {
    province_number: '0014',
    province_name: '山西',
    cities: [
      { city_number: '1401', city_name: '太原' },
      { city_number: '1402', city_name: '长治' },
      { city_number: '1403', city_name: '大同' },
      { city_number: '1404', city_name: '晋城' },
      { city_number: '1405', city_name: '离石' },
      { city_number: '1406', city_name: '临汾' },
      { city_number: '1407', city_name: '朔州' },
      { city_number: '1408', city_name: '忻州' },
      { city_number: '1409', city_name: '阳泉' },
      { city_number: '1410', city_name: '榆次' },
      { city_number: '1411', city_name: '运城' },
      { city_number: '1412', city_name: '晋中' },
      { city_number: '1413', city_name: '吕梁' },
    ],
  },
  {
    province_number: '0015',
    province_name: '内蒙古',
    cities: [
      { city_number: '1501', city_name: '呼和浩特' },
      { city_number: '1502', city_name: '包头' },
      { city_number: '1503', city_name: '阿拉善' },
      { city_number: '1504', city_name: '巴彦淖尔' },
      { city_number: '1505', city_name: '赤峰' },
      { city_number: '1506', city_name: '呼伦贝尔' },
      { city_number: '1507', city_name: '乌海' },
      { city_number: '1508', city_name: '乌兰察布' },
      { city_number: '1509', city_name: '锡林郭勒' },
      { city_number: '1510', city_name: '兴安' },
      { city_number: '1511', city_name: '鄂尔多斯' },
      { city_number: '1512', city_name: '通辽' },
    ],
  },
  {
    province_number: '0021',
    province_name: '辽宁',
    cities: [
      { city_number: '2101', city_name: '沈阳' },
      { city_number: '2102', city_name: '大连' },
      { city_number: '2103', city_name: '鞍山' },
      { city_number: '2104', city_name: '本溪' },
      { city_number: '2105', city_name: '朝阳' },
      { city_number: '2106', city_name: '丹东' },
      { city_number: '2107', city_name: '抚顺' },
      { city_number: '2108', city_name: '阜新' },
      { city_number: '2109', city_name: '葫芦岛' },
      { city_number: '2110', city_name: '锦州' },
      { city_number: '2111', city_name: '辽阳' },
      { city_number: '2112', city_name: '盘锦' },
      { city_number: '2113', city_name: '铁岭' },
      { city_number: '2114', city_name: '营口' },
    ],
  },
  {
    province_number: '0022',
    province_name: '吉林',
    cities: [
      { city_number: '2201', city_name: '长春' },
      { city_number: '2202', city_name: '白城' },
      { city_number: '2203', city_name: '白山' },
      { city_number: '2204', city_name: '吉林' },
      { city_number: '2205', city_name: '辽源' },
      { city_number: '2206', city_name: '四平' },
      { city_number: '2207', city_name: '松原' },
      { city_number: '2208', city_name: '通化' },
      { city_number: '2209', city_name: '延边' },
    ],
  },
  {
    province_number: '0023',
    province_name: '黑龙江',
    cities: [
      { city_number: '2301', city_name: '哈尔滨' },
      { city_number: '2302', city_name: '大庆' },
      { city_number: '2303', city_name: '大兴安岭' },
      { city_number: '2304', city_name: '鹤岗' },
      { city_number: '2305', city_name: '黑河' },
      { city_number: '2306', city_name: '鸡西' },
      { city_number: '2307', city_name: '佳木斯' },
      { city_number: '2308', city_name: '牡丹江' },
      { city_number: '2309', city_name: '七台河' },
      { city_number: '2310', city_name: '齐齐哈尔' },
      { city_number: '2311', city_name: '双鸭山' },
      { city_number: '2312', city_name: '绥化' },
      { city_number: '2313', city_name: '伊春' },
    ],
  },
  {
    province_number: '0031',
    province_name: '上海',
    cities: [{ city_number: '3100', city_name: '上海' }],
  },
  {
    province_number: '0032',
    province_name: '江苏',
    cities: [
      { city_number: '3201', city_name: '南京' },
      { city_number: '3202', city_name: '常州' },
      { city_number: '3203', city_name: '淮安' },
      { city_number: '3204', city_name: '连云港' },
      { city_number: '3205', city_name: '南通' },
      { city_number: '3206', city_name: '苏州' },
      { city_number: '3207', city_name: '宿迁' },
      { city_number: '3208', city_name: '泰州' },
      { city_number: '3209', city_name: '无锡' },
      { city_number: '3210', city_name: '徐州' },
      { city_number: '3211', city_name: '盐城' },
      { city_number: '3212', city_name: '扬州' },
      { city_number: '3213', city_name: '镇江' },
      { city_number: '3214', city_name: '胥浦' },
    ],
  },
  {
    province_number: '0033',
    province_name: '浙江',
    cities: [
      { city_number: '3301', city_name: '杭州' },
      { city_number: '3302', city_name: '宁波' },
      { city_number: '3303', city_name: '湖州' },
      { city_number: '3304', city_name: '嘉兴' },
      { city_number: '3305', city_name: '金华' },
      { city_number: '3306', city_name: '绍兴' },
      { city_number: '3307', city_name: '台州' },
      { city_number: '3308', city_name: '温州' },
      { city_number: '3309', city_name: '舟山' },
      { city_number: '3310', city_name: '衢州' },
      { city_number: '3311', city_name: '丽水' },
    ],
  },
  {
    province_number: '0034',
    province_name: '安徽',
    cities: [
      { city_number: '3401', city_name: '合肥' },
      { city_number: '3402', city_name: '安庆' },
      { city_number: '3403', city_name: '蚌埠' },
      { city_number: '3404', city_name: '巢湖' },
      { city_number: '3405', city_name: '池州' },
      { city_number: '3406', city_name: '滁州' },
      { city_number: '3407', city_name: '阜阳' },
      { city_number: '3408', city_name: '淮北' },
      { city_number: '3409', city_name: '淮南' },
      { city_number: '3410', city_name: '黄山' },
      { city_number: '3411', city_name: '六安' },
      { city_number: '3412', city_name: '马鞍山' },
      { city_number: '3414', city_name: '铜陵' },
      { city_number: '3415', city_name: '芜湖' },
      { city_number: '3416', city_name: '宣城' },
      { city_number: '3417', city_name: '亳州' },
      { city_number: '3418', city_name: '宿州' },
    ],
  },
  {
    province_number: '0035',
    province_name: '福建',
    cities: [
      { city_number: '3501', city_name: '福州' },
      { city_number: '3502', city_name: '厦门' },
      { city_number: '3503', city_name: '龙岩' },
      { city_number: '3504', city_name: '南平' },
      { city_number: '3505', city_name: '宁德' },
      { city_number: '3506', city_name: '莆田' },
      { city_number: '3507', city_name: '泉州' },
      { city_number: '3508', city_name: '三明' },
      { city_number: '3509', city_name: '漳州' },
    ],
  },
  {
    province_number: '0036',
    province_name: '江西',
    cities: [
      { city_number: '3601', city_name: '南昌' },
      { city_number: '3602', city_name: '抚州' },
      { city_number: '3603', city_name: '赣州' },
      { city_number: '3604', city_name: '吉安' },
      { city_number: '3605', city_name: '景德镇' },
      { city_number: '3606', city_name: '九江' },
      { city_number: '3607', city_name: '萍乡' },
      { city_number: '3608', city_name: '上饶' },
      { city_number: '3609', city_name: '新余' },
      { city_number: '3610', city_name: '宜春' },
      { city_number: '3611', city_name: '鹰潭' },
    ],
  },
  {
    province_number: '0037',
    province_name: '山东',
    cities: [
      { city_number: '3701', city_name: '济南' },
      { city_number: '3702', city_name: '青岛' },
      { city_number: '3703', city_name: '滨州' },
      { city_number: '3704', city_name: '德州' },
      { city_number: '3705', city_name: '东营' },
      { city_number: '3706', city_name: '菏泽' },
      { city_number: '3707', city_name: '济宁' },
      { city_number: '3708', city_name: '莱芜' },
      { city_number: '3709', city_name: '聊城' },
      { city_number: '3710', city_name: '临沂' },
      { city_number: '3711', city_name: '日照' },
      { city_number: '3712', city_name: '泰安' },
      { city_number: '3713', city_name: '威海' },
      { city_number: '3714', city_name: '潍坊' },
      { city_number: '3715', city_name: '烟台' },
      { city_number: '3716', city_name: '枣庄' },
      { city_number: '3717', city_name: '淄博' },
    ],
  },
  {
    province_number: '0041',
    province_name: '河南',
    cities: [
      { city_number: '4101', city_name: '郑州' },
      { city_number: '4102', city_name: '安阳' },
      { city_number: '4103', city_name: '焦作' },
      { city_number: '4104', city_name: '鹤壁' },
      { city_number: '4105', city_name: '开封' },
      { city_number: '4106', city_name: '洛阳' },
      { city_number: '4107', city_name: '南阳' },
      { city_number: '4108', city_name: '平顶山' },
      { city_number: '4109', city_name: '三门峡' },
      { city_number: '4110', city_name: '商丘' },
      { city_number: '4111', city_name: '新乡' },
      { city_number: '4112', city_name: '信阳' },
      { city_number: '4113', city_name: '许昌' },
      { city_number: '4114', city_name: '周口' },
      { city_number: '4115', city_name: '驻马店' },
      { city_number: '4116', city_name: '漯河' },
      { city_number: '4117', city_name: '濮阳' },
      { city_number: '4118', city_name: '济源' },
    ],
  },
  {
    province_number: '0042',
    province_name: '湖北',
    cities: [
      { city_number: '4201', city_name: '武汉' },
      { city_number: '4202', city_name: '鄂州' },
      { city_number: '4203', city_name: '恩施' },
      { city_number: '4204', city_name: '黄冈' },
      { city_number: '4205', city_name: '黄石' },
      { city_number: '4206', city_name: '荆门' },
      { city_number: '4207', city_name: '荆州' },
      { city_number: '4208', city_name: '十堰' },
      { city_number: '4209', city_name: '随州' },
      { city_number: '4210', city_name: '咸宁' },
      { city_number: '4211', city_name: '襄樊' },
      { city_number: '4212', city_name: '孝感' },
      { city_number: '4213', city_name: '神农架' },
      { city_number: '4214', city_name: '天门' },
      { city_number: '4215', city_name: '宜昌' },
      { city_number: '4216', city_name: '三峡' },
    ],
  },
  {
    province_number: '0043',
    province_name: '湖南',
    cities: [
      { city_number: '4301', city_name: '长沙' },
      { city_number: '4302', city_name: '常德' },
      { city_number: '4303', city_name: '郴州' },
      { city_number: '4304', city_name: '衡阳' },
      { city_number: '4305', city_name: '怀化' },
      { city_number: '4306', city_name: '娄底' },
      { city_number: '4307', city_name: '邵阳' },
      { city_number: '4308', city_name: '湘潭' },
      { city_number: '4309', city_name: '湘西' },
      { city_number: '4310', city_name: '益阳' },
      { city_number: '4311', city_name: '永州' },
      { city_number: '4312', city_name: '岳阳' },
      { city_number: '4313', city_name: '张家界' },
      { city_number: '4314', city_name: '株洲' },
    ],
  },
  {
    province_number: '0044',
    province_name: '广东',
    cities: [
      { city_number: '4401', city_name: '广州' },
      { city_number: '4402', city_name: '深圳' },
      { city_number: '4403', city_name: '潮州' },
      { city_number: '4404', city_name: '东莞' },
      { city_number: '4405', city_name: '佛山' },
      { city_number: '4406', city_name: '惠州' },
      { city_number: '4407', city_name: '江门' },
      { city_number: '4408', city_name: '揭阳' },
      { city_number: '4409', city_name: '茂名' },
      { city_number: '4410', city_name: '梅州' },
      { city_number: '4411', city_name: '清远' },
      { city_number: '4412', city_name: '汕头' },
      { city_number: '4413', city_name: '汕尾' },
      { city_number: '4414', city_name: '韶关' },
      { city_number: '4415', city_name: '阳江' },
      { city_number: '4416', city_name: '云浮' },
      { city_number: '4417', city_name: '湛江' },
      { city_number: '4418', city_name: '肇庆' },
      { city_number: '4419', city_name: '中山' },
      { city_number: '4420', city_name: '河源' },
      { city_number: '4421', city_name: '珠海' },
    ],
  },
  {
    province_number: '0045',
    province_name: '广西',
    cities: [
      { city_number: '4501', city_name: '南宁' },
      { city_number: '4502', city_name: '百色' },
      { city_number: '4503', city_name: '北海' },
      { city_number: '4504', city_name: '桂林' },
      { city_number: '4505', city_name: '河池' },
      { city_number: '4506', city_name: '柳州' },
      { city_number: '4507', city_name: '梧州' },
      { city_number: '4508', city_name: '玉林' },
      { city_number: '4509', city_name: '崇左' },
      { city_number: '4510', city_name: '防城港' },
      { city_number: '4511', city_name: '贵港' },
      { city_number: '4512', city_name: '贺州' },
      { city_number: '4513', city_name: '来宾' },
      { city_number: '4514', city_name: '钦州' },
    ],
  },
  {
    province_number: '0046',
    province_name: '海南',
    cities: [
      { city_number: '4601', city_name: '海口' },
      { city_number: '4602', city_name: '三亚' },
      { city_number: '4603', city_name: '白沙' },
      { city_number: '4604', city_name: '保亭' },
      { city_number: '4605', city_name: '昌江' },
      { city_number: '4606', city_name: '澄迈' },
      { city_number: '4607', city_name: '儋州' },
      { city_number: '4608', city_name: '定安' },
      { city_number: '4609', city_name: '东方' },
      { city_number: '4610', city_name: '乐东' },
      { city_number: '4611', city_name: '临高' },
      { city_number: '4612', city_name: '陵水' },
      { city_number: '4613', city_name: '琼海' },
      { city_number: '4614', city_name: '琼中' },
      { city_number: '4615', city_name: '屯昌' },
      { city_number: '4616', city_name: '万宁' },
      { city_number: '4617', city_name: '文昌' },
      { city_number: '4618', city_name: '五指山' },
      { city_number: '4619', city_name: '洋浦' },
    ],
  },
  {
    province_number: '0050',
    province_name: '重庆',
    cities: [{ city_number: '5000', city_name: '重庆' }],
  },
  {
    province_number: '0051',
    province_name: '四川',
    cities: [
      { city_number: '5101', city_name: '成都' },
      { city_number: '5102', city_name: '巴中' },
      { city_number: '5103', city_name: '达州' },
      { city_number: '5104', city_name: '德阳' },
      { city_number: '5105', city_name: '广安' },
      { city_number: '5106', city_name: '广元' },
      { city_number: '5107', city_name: '乐山' },
      { city_number: '5108', city_name: '凉山' },
      { city_number: '5109', city_name: '眉山' },
      { city_number: '5110', city_name: '绵阳' },
      { city_number: '5111', city_name: '南充' },
      { city_number: '5112', city_name: '内江' },
      { city_number: '5113', city_name: '攀枝花' },
      { city_number: '5114', city_name: '遂宁' },
      { city_number: '5115', city_name: '雅安' },
      { city_number: '5116', city_name: '宜宾' },
      { city_number: '5117', city_name: '自贡' },
      { city_number: '5118', city_name: '泸州' },
      { city_number: '5119', city_name: '阿坝' },
      { city_number: '5120', city_name: '甘孜' },
      { city_number: '5121', city_name: '资阳' },
    ],
  },
  {
    province_number: '0052',
    province_name: '贵州',
    cities: [
      { city_number: '5201', city_name: '贵阳' },
      { city_number: '5202', city_name: '安顺' },
      { city_number: '5203', city_name: '毕节' },
      { city_number: '5204', city_name: '六盘水' },
      { city_number: '5205', city_name: '铜仁' },
      { city_number: '5206', city_name: '遵义' },
      { city_number: '5207', city_name: '黔东南' },
      { city_number: '5208', city_name: '黔南' },
      { city_number: '5209', city_name: '黔西南' },
    ],
  },
  {
    province_number: '0053',
    province_name: '云南',
    cities: [
      { city_number: '5301', city_name: '昆明' },
      { city_number: '5302', city_name: '西双版纳' },
      { city_number: '5303', city_name: '保山' },
      { city_number: '5304', city_name: '楚雄' },
      { city_number: '5305', city_name: '大理' },
      { city_number: '5306', city_name: '德宏' },
      { city_number: '5307', city_name: '红河' },
      { city_number: '5308', city_name: '丽江' },
      { city_number: '5309', city_name: '临沧' },
      { city_number: '5310', city_name: '怒江' },
      { city_number: '5311', city_name: '曲靖' },
      { city_number: '5312', city_name: '思茅' },
      { city_number: '5313', city_name: '文山' },
      { city_number: '5314', city_name: '玉溪' },
      { city_number: '5315', city_name: '昭通' },
      { city_number: '5316', city_name: '中甸' },
      { city_number: '5317', city_name: '迪庆州' },
    ],
  },
  {
    province_number: '0054',
    province_name: '西藏',
    cities: [
      { city_number: '5401', city_name: '拉萨' },
      { city_number: '5402', city_name: '阿里' },
      { city_number: '5403', city_name: '昌都' },
      { city_number: '5404', city_name: '林芝' },
      { city_number: '5405', city_name: '那曲' },
      { city_number: '5406', city_name: '日喀则' },
      { city_number: '5407', city_name: '山南' },
    ],
  },
  {
    province_number: '0061',
    province_name: '陕西',
    cities: [
      { city_number: '6101', city_name: '西安' },
      { city_number: '6102', city_name: '安康' },
      { city_number: '6103', city_name: '宝鸡' },
      { city_number: '6104', city_name: '汉中' },
      { city_number: '6105', city_name: '商洛' },
      { city_number: '6106', city_name: '铜川' },
      { city_number: '6107', city_name: '渭南' },
      { city_number: '6108', city_name: '咸阳' },
      { city_number: '6109', city_name: '延安' },
      { city_number: '6110', city_name: '榆林' },
    ],
  },
  {
    province_number: '0062',
    province_name: '甘肃',
    cities: [
      { city_number: '6201', city_name: '兰州' },
      { city_number: '6202', city_name: '白银' },
      { city_number: '6203', city_name: '定西' },
      { city_number: '6204', city_name: '东风' },
      { city_number: '6205', city_name: '合作' },
      { city_number: '6206', city_name: '嘉峪关' },
      { city_number: '6207', city_name: '金昌' },
      { city_number: '6208', city_name: '酒泉' },
      { city_number: '6209', city_name: '矿区' },
      { city_number: '6210', city_name: '临夏' },
      { city_number: '6211', city_name: '陇南' },
      { city_number: '6212', city_name: '平凉' },
      { city_number: '6213', city_name: '庆阳' },
      { city_number: '6214', city_name: '天水' },
      { city_number: '6215', city_name: '武威' },
      { city_number: '6216', city_name: '张掖' },
      { city_number: '6217', city_name: '甘南州' },
    ],
  },
  {
    province_number: '0063',
    province_name: '青海',
    cities: [
      { city_number: '6301', city_name: '西宁' },
      { city_number: '6302', city_name: '海东' },
    ],
  },
  {
    province_number: '0064',
    province_name: '宁夏',
    cities: [
      { city_number: '6401', city_name: '银川' },
      { city_number: '6402', city_name: '中卫' },
      { city_number: '6403', city_name: '固原' },
      { city_number: '6404', city_name: '石嘴山' },
      { city_number: '6405', city_name: '吴忠' },
    ],
  },
  {
    province_number: '0065',
    province_name: '新疆',
    cities: [
      { city_number: '6501', city_name: '乌鲁木齐' },
      { city_number: '6502', city_name: '阿克苏' },
      { city_number: '6503', city_name: '阿勒泰' },
      { city_number: '6504', city_name: '巴州' },
      { city_number: '6505', city_name: '博州' },
      { city_number: '6506', city_name: '昌吉' },
      { city_number: '6507', city_name: '哈密' },
      { city_number: '6508', city_name: '和田' },
      { city_number: '6509', city_name: '喀什' },
      { city_number: '6510', city_name: '克拉玛依' },
      { city_number: '6511', city_name: '马兰' },
      { city_number: '6512', city_name: '石河子' },
      { city_number: '6513', city_name: '塔城' },
      { city_number: '6514', city_name: '吐鲁番' },
      { city_number: '6515', city_name: '伊犁' },
      { city_number: '6516', city_name: '克州' },
      { city_number: '6517', city_name: '阿拉尔' },
      { city_number: '6518', city_name: '五家渠' },
    ],
  },
  {
    province_number: '2001',
    province_name: '香港',
    cities: [{ city_number: '9901', city_name: '香港' }],
  },
  {
    province_number: '2002',
    province_name: '澳门',
    cities: [{ city_number: '9902', city_name: '澳门' }],
  },
  {
    province_number: '2003',
    province_name: '台湾',
    cities: [{ city_number: '9903', city_name: '台湾' }],
  },
];
export default area;
